package in.sevasuyog.model.enums;

public enum ResponseMessage {
	SUCCESSFUL,
	INCORRECT_PASSWORD,
	NOT_VERIFIED,
	BLOCKED,
	SOMETHING_WENT_WRONG, 
	OPERATION_NOT_ALLOWED, 
	ENTITY_NOT_FOUND, 
	INVALID_SESSION, 
	INCORRECT_USERNAME
}
